name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean verify
    - name: Create deployment JAR
      run: mvn package -DskipTests
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: HackTheStrategy
        path: target/*.jar